package org.srluren.web.beans.hb;

// Generated 29/10/2012 01:48:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoPersona generated by hbm2java
 */
public class TipoPersona implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTipoPersona;
	private String descriptiva;
	private String nemonico;
	private Date fechaReg;
	private Date fechaAct;
	private Date fechaEli;
	private Set<Tasa> tasas = new HashSet<Tasa>(0);

	public TipoPersona() {
	}

	public TipoPersona(Integer idTipoPersona, String descriptiva, String nemonico) {
		this.idTipoPersona = idTipoPersona;
		this.descriptiva = descriptiva;
		this.nemonico = nemonico;
	}

	public TipoPersona(Integer idTipoPersona, String descriptiva, String nemonico,
			Date fechaReg, Date fechaAct, Date fechaEli, Set<Tasa> tasas) {
		this.idTipoPersona = idTipoPersona;
		this.descriptiva = descriptiva;
		this.nemonico = nemonico;
		this.fechaReg = fechaReg;
		this.fechaAct = fechaAct;
		this.fechaEli = fechaEli;
		this.tasas = tasas;
	}

	public Integer getIdTipoPersona() {
		return this.idTipoPersona;
	}

	public void setIdTipoPersona(Integer idTipoPersona) {
		this.idTipoPersona = idTipoPersona;
	}

	public String getDescriptiva() {
		return this.descriptiva;
	}

	public void setDescriptiva(String descriptiva) {
		this.descriptiva = descriptiva;
	}

	public String getNemonico() {
		return this.nemonico;
	}

	public void setNemonico(String nemonico) {
		this.nemonico = nemonico;
	}

	public Date getFechaReg() {
		return this.fechaReg;
	}

	public void setFechaReg(Date fechaReg) {
		this.fechaReg = fechaReg;
	}

	public Date getFechaAct() {
		return this.fechaAct;
	}

	public void setFechaAct(Date fechaAct) {
		this.fechaAct = fechaAct;
	}

	public Date getFechaEli() {
		return this.fechaEli;
	}

	public void setFechaEli(Date fechaEli) {
		this.fechaEli = fechaEli;
	}

	public Set<Tasa> getTasas() {
		return this.tasas;
	}

	public void setTasas(Set<Tasa> tasas) {
		this.tasas = tasas;
	}

}
