package org.srluren.web.beans.hb;

// Generated 27/03/2013 12:17:29 AM by Hibernate Tools 3.4.0.CR1

/**
 * Parametro generated by hbm2java
 */
public class Parametro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idParametro;
	private String tipoPar;
	private String valorPar;
	private String descrPar;

	public Parametro() {
	}

	public Parametro(int idParametro) {
		this.idParametro = idParametro;
	}

	public Parametro(int idParametro, String tipoPar, String valorPar,
			String descrPar) {
		this.idParametro = idParametro;
		this.tipoPar = tipoPar;
		this.valorPar = valorPar;
		this.descrPar = descrPar;
	}

	public int getIdParametro() {
		return this.idParametro;
	}

	public void setIdParametro(int idParametro) {
		this.idParametro = idParametro;
	}

	public String getTipoPar() {
		return this.tipoPar;
	}

	public void setTipoPar(String tipoPar) {
		this.tipoPar = tipoPar;
	}

	public String getValorPar() {
		return this.valorPar;
	}

	public void setValorPar(String valorPar) {
		this.valorPar = valorPar;
	}

	public String getDescrPar() {
		return this.descrPar;
	}

	public void setDescrPar(String descrPar) {
		this.descrPar = descrPar;
	}

}
