package org.srluren.admin.beans.hb;

// Generated 29/10/2012 01:48:07 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Tasa generated by hbm2java
 */
public class Tasa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTasa;
	private Moneda moneda;
	private SubProducto subProducto;
	private TipoPersona tipoPersona;
	private long mtoInicial;
	private long mtoFinal;
	private BigDecimal valTasaMin;
	private BigDecimal valTasaMax;
	private Integer plazoInicial;
	private Integer plazoFinal;
	private String descripcionPlazo;
	private int unidadPlazo;
	private Integer rango;
	private Date fechaReg;
	private Date fechaAct;
	private Date fechaEli;

	public Tasa() {
	}

	public Tasa(Integer idTasa, Moneda moneda, SubProducto subProducto,
			TipoPersona tipoPersona, long mtoInicial, long mtoFinal,
			BigDecimal valTasaMin, BigDecimal valTasaMax) {
		this.idTasa = idTasa;
		this.moneda = moneda;
		this.subProducto = subProducto;
		this.tipoPersona = tipoPersona;
		this.mtoInicial = mtoInicial;
		this.mtoFinal = mtoFinal;
		this.valTasaMin = valTasaMin;
		this.valTasaMax = valTasaMax;
	}

	public Tasa(Integer idTasa, Moneda moneda, SubProducto subProducto,
			TipoPersona tipoPersona, long mtoInicial, long mtoFinal,
			BigDecimal valTasa, Integer rango, Date fechaReg, Date fechaAct,
			Date fechaEli) {
		this.idTasa = idTasa;
		this.moneda = moneda;
		this.subProducto = subProducto;
		this.tipoPersona = tipoPersona;
		this.mtoInicial = mtoInicial;
		this.mtoFinal = mtoFinal;
		this.rango = rango;
		this.fechaReg = fechaReg;
		this.fechaAct = fechaAct;
		this.fechaEli = fechaEli;
	}

	public Integer getIdTasa() {
		return this.idTasa;
	}

	public void setIdTasa(Integer idTasa) {
		this.idTasa = idTasa;
	}

	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	public SubProducto getSubProductos() {
		return this.subProducto;
	}

	public void setSubProductos(SubProducto subProducto) {
		this.subProducto = subProducto;
	}

	public TipoPersona getTipoPersona() {
		return this.tipoPersona;
	}

	public void setTipoPersona(TipoPersona tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	public long getMtoInicial() {
		return this.mtoInicial;
	}

	public void setMtoInicial(long mtoInicial) {
		this.mtoInicial = mtoInicial;
	}

	public long getMtoFinal() {
		return this.mtoFinal;
	}

	public void setMtoFinal(long mtoFinal) {
		this.mtoFinal = mtoFinal;
	}
	
	public Integer getRango() {
		return this.rango;
	}

	public void setRango(Integer rango) {
		this.rango = rango;
	}

	public Date getFechaReg() {
		return this.fechaReg;
	}

	public void setFechaReg(Date fechaReg) {
		this.fechaReg = fechaReg;
	}

	public Date getFechaAct() {
		return this.fechaAct;
	}

	public void setFechaAct(Date fechaAct) {
		this.fechaAct = fechaAct;
	}

	public Date getFechaEli() {
		return this.fechaEli;
	}

	public void setFechaEli(Date fechaEli) {
		this.fechaEli = fechaEli;
	}

	public BigDecimal getValTasaMin() {
		return valTasaMin;
	}

	public void setValTasaMin(BigDecimal valTasaMin) {
		this.valTasaMin = valTasaMin;
	}

	public BigDecimal getValTasaMax() {
		return valTasaMax;
	}

	public void setValTasaMax(BigDecimal valTasaMax) {
		this.valTasaMax = valTasaMax;
	}

	public Integer getPlazoInicial() {
		return plazoInicial;
	}

	public void setPlazoInicial(Integer plazoInicial) {
		this.plazoInicial = plazoInicial;
	}

	public Integer getPlazoFinal() {
		return plazoFinal;
	}

	public void setPlazoFinal(Integer plazoFinal) {
		this.plazoFinal = plazoFinal;
	}

	public String getDescripcionPlazo() {
		return descripcionPlazo;
	}

	public void setDescripcionPlazo(String descripcionPlazo) {
		this.descripcionPlazo = descripcionPlazo;
	}

	public int getUnidadPlazo() {
		return unidadPlazo;
	}

	public void setUnidadPlazo(int unidadPlazo) {
		this.unidadPlazo = unidadPlazo;
	}
	
	

}
