package org.srluren.admin.beans.bckp;

// Generated 29/10/2012 01:48:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idProductos;
	private String nombre;
	private String nemonico;
	private String tipo;
	private Date fechaReg;
	private Date fechaAct;
	private Date fechaEli;
	private Set<SubProducto> subProductoses = new HashSet<SubProducto>(0);

	public Producto() {
	}

	public Producto(Integer idProductos, String nombre, String nemonico,
			String tipo) {
		this.idProductos = idProductos;
		this.nombre = nombre;
		this.nemonico = nemonico;
		this.tipo = tipo;
	}

	public Producto(Integer idProductos, String nombre, String nemonico,
			String tipo, Date fechaReg, Date fechaAct, Date fechaEli,
			Set<SubProducto> subProductoses) {
		this.idProductos = idProductos;
		this.nombre = nombre;
		this.nemonico = nemonico;
		this.tipo = tipo;
		this.fechaReg = fechaReg;
		this.fechaAct = fechaAct;
		this.fechaEli = fechaEli;
		this.subProductoses = subProductoses;
	}

	public Integer getIdProductos() {
		return this.idProductos;
	}

	public void setIdProductos(Integer idProductos) {
		this.idProductos = idProductos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getNemonico() {
		return this.nemonico;
	}

	public void setNemonico(String nemonico) {
		this.nemonico = nemonico;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Date getFechaReg() {
		return this.fechaReg;
	}

	public void setFechaReg(Date fechaReg) {
		this.fechaReg = fechaReg;
	}

	public Date getFechaAct() {
		return this.fechaAct;
	}

	public void setFechaAct(Date fechaAct) {
		this.fechaAct = fechaAct;
	}

	public Date getFechaEli() {
		return this.fechaEli;
	}

	public void setFechaEli(Date fechaEli) {
		this.fechaEli = fechaEli;
	}

	public Set<SubProducto> getSubProductoses() {
		return this.subProductoses;
	}

	public void setSubProductoses(Set<SubProducto> subProductoses) {
		this.subProductoses = subProductoses;
	}

}
